### ISSUE TITLE
Improve doc

### ISSUE THREAD

**Issue by LuizFellype** [julio-bandeira/pyhton_weaver#1]
Add in README the prerequisites and how to run the project.

**Comment by julio-bandeira** [comment]
@LuizFellype thank you for your suggestion, I am fixing a little bug and will commit with a new README with the instructions on how to run and install the necessary package. When finished I will notificate and close the issue.

**Comment by LuizFellype** [comment]
Welcome man.
Just curious, where are you from ?
Because your name is very common here in Brasil.



Em sex, 7 de ago de 2020 4:50 PM, Julio Bandeira de Carvalho <
notifications@github.com> escreveu:

**Comment by julio-bandeira** [comment]
I am from Brazil too 😄 São Paulo, Capital
Não tenho muito tempo na programação, estou criando costume agora com Git e GitHub, então meus README não são tão adequados 😆

**Comment by julio-bandeira** [comment]
I am from Brazil too 😄 São Paulo, Capital
Não tenho muito tempo na programação, estou criando costume agora com Git e GitHub, então meus README não são tão adequados 😆

**Comment by LuizFellype** [comment]
Bem que reparei kkkkkkkk sou de ES, Vitória.
Pow irmão, se quiser trocar uma ideia manda msg no wpp, acho que é melhor
que email.
27988521801

Em sex, 7 de ago de 2020 6:10 PM, Julio Bandeira de Carvalho <
notifications@github.com> escreveu:

**Comment by julio-bandeira** [comment]
Pronto organizado e informado sobre os requisitos e o método de execução, se possível me informe se falta mais alguma coisa, caso tudo certo fecharei a issue...

kkk obrigado qualquer coisa chamo sim, realmente concordo é muito melhor que o e-mail, obrigado pela colaboração

> Bem que reparei kkkkkkkk sou de ES, Vitória. Pow irmão, se quiser trocar uma ideia manda msg no wpp, acho que é melhor que email. 27988521801
